### ISSUE TITLE
能请问下使用cnn的原因吗？

### ISSUE THREAD

**Issue by yzho0907** [Wangpeiyi9979/IE-Bert-CNN#4]
会不会出现比较多的情况，比如，实体不全（北京大学，但抽取出北京大）或者过长（北京，但北京大）呢？

**Comment by wangbq18** [comment]
我跑了一下这个模型发现召回很高，精度很低，很大一部分原因是实体抽取不全，很多实体被拆分成两个部分被识别出来

**Comment by yzho0907** [comment]
这是因为模型对实体作为一个整体没有很好的学习

**Comment by wangbq18** [comment]
我也跑了一下BERT+CRF发现问题并没有得到解决f1更低，

**Comment by yzho0907** [comment]
@wangbq18 我也有同样的问题...

**Comment by wangbq18** [comment]
很多实体被分成这个形式B I I O I I O  B I O O I I,

**Comment by wangbq18** [comment]
@Wangpeiyi9979 @yzho0907 如果有解决方案希望能告知

**Comment by Wangpeiyi9979** [comment]
> 会不会出现比较多的情况，比如，实体不全（北京大学，但抽取出北京大）或者过长（北京，但北京大）呢？

我记得代码结束后，out文件夹下会输出实体tag标签的预测结果，当初我检查的时候感觉这样的情况不多。

**Comment by Wangpeiyi9979** [comment]
> 我跑了一下这个模型发现召回很高，精度很低，很大一部分原因是实体抽取不全，很多实体被拆分成两个部分被识别出来

召回很高，精确很低有一个比较重要的原因是官方数据验证集本来就有错误标注，在线上提交的时候，准确率比召回率要高。
![image](https://user-images.githubusercontent.com/42565075/58099298-ef235500-7c0d-11e9-8412-69c71ef5df15.png)

**Comment by Wangpeiyi9979** [comment]
> 我也跑了一下BERT+CRF发现问题并没有得到解决f1更低，

这个例子中接入CRF效果确实是比不接要差的，在BERT原文中也提到了做命名实体识别后不必要再接CRF。这里代码只是做了个简单的测试。所以还是建议不接CRF。

**Comment by wangbq18** [comment]
> > 我跑了一下这个模型发现召回很高，精度很低，很大一部分原因是实体抽取不全，很多实体被拆分成两个部分被识别出来
> 
> 召回很高，精确很低有一个比较重要的原因是官方数据验证集本来就有错误标注，在线上提交的时候，准确率比召回率要高。
> ![image](https://user-images.githubusercontent.com/42565075/58099298-ef235500-7c0d-11e9-8412-69c71ef5df15.png)

难道是我的原因？我线下训练时acc 0.73+ recall 0.81+

**Comment by Wangpeiyi9979** [comment]
模型流程是先进行命名实体识别，然后进行实体间的匹配(根据实体类型只匹配可能存在关系的实体），然后我将匹配出的两个实体和两个实体间的文字截取出来，使用CNN学习出一个特征向量，进行关系分类。
不过我觉得这个设计可能并不是很好，因为结果只有0.81，我看比赛结果好多基于BERT的能够达到0.84，甚至0.86.

**Comment by Wangpeiyi9979** [comment]
> > > 我跑了一下这个模型发现召回很高，精度很低，很大一部分原因是实体抽取不全，很多实体被拆分成两个部分被识别出来
> > 
> > 
> > 召回很高，精确很低有一个比较重要的原因是官方数据验证集本来就有错误标注，在线上提交的时候，准确率比召回率要高。
> > ![image](https://user-images.githubusercontent.com/42565075/58099298-ef235500-7c0d-11e9-8412-69c71ef5df15.png)
> 
> 难道是我的原因？我线下训练时acc 0.73+ recall 0.81+

线下确实是recall比较高，我感觉应该是数据标注的问题。。

**Comment by wangbq18** [comment]
> 模型流程是先进行命名实体识别，然后进行实体间的匹配(根据实体类型只匹配可能存在关系的实体），然后我将匹配出的两个实体和两个实体间的文字截取出来，使用CNN学习出一个特征向量，进行关系分类。
> 不过我觉得这个设计可能并不是很好，因为结果只有0.81，我看比赛结果好多基于BERT的能够达到0.84，甚至0.86.

对的，我觉得是在实体对匹配过程，或者实体截取时除了问题，我这边recall很高，对分出来的错误实体简单过滤或者纠正，能提升2个点左右，你的这个模型可以在琢磨琢磨，有很大优化空间

**Comment by Wangpeiyi9979** [comment]
> > 模型流程是先进行命名实体识别，然后进行实体间的匹配(根据实体类型只匹配可能存在关系的实体），然后我将匹配出的两个实体和两个实体间的文字截取出来，使用CNN学习出一个特征向量，进行关系分类。
> > 不过我觉得这个设计可能并不是很好，因为结果只有0.81，我看比赛结果好多基于BERT的能够达到0.84，甚至0.86.
> 
> 对的，我觉得是在实体对匹配过程，或者实体截取时除了问题，我这边recall很高，对分出来的错误实体简单过滤或者纠正，能提升2个点左右，你的这个模型可以在琢磨琢磨，有很大优化空间

最近在准备保研的事情，等忙过这段时间，再好好研究一下排名靠前的BERT模型，如果您有优化，也希望您能指教，谢谢您，祝您生活愉快！

**Comment by wangbq18** [comment]
> > 会不会出现比较多的情况，比如，实体不全（北京大学，但抽取出北京大）或者过长（北京，但北京大）呢？
> 
> 我记得代码结束后，out文件夹下会输出实体tag标签的预测结果，当初我检查的时候感觉这样的情况不多

> > > 模型流程是先进行命名实体识别，然后进行实体间的匹配(根据实体类型只匹配可能存在关系的实体），然后我将匹配出的两个实体和两个实体间的文字截取出来，使用CNN学习出一个特征向量，进行关系分类。
> > > 不过我觉得这个设计可能并不是很好，因为结果只有0.81，我看比赛结果好多基于BERT的能够达到0.84，甚至0.86.
> > 
> > 
> > 对的，我觉得是在实体对匹配过程，或者实体截取时除了问题，我这边recall很高，对分出来的错误实体简单过滤或者纠正，能提升2个点左右，你的这个模型可以在琢磨琢磨，有很大优化空间
> 
> 最近在准备保研的事情，等忙过这段时间，再好好研究一下排名靠前的BERT模型，如果您有优化，也希望您能指教，谢谢您，祝您生活愉快！

你还是本科生啊，很厉害啊，你的这个模型是自己设计的吗，有参考文献吗？有的话希望能告知，也祝你保研顺利！

**Comment by yzho0907** [comment]
@Wangpeiyi9979 祝顺

**Comment by Wangpeiyi9979** [comment]
> > > 会不会出现比较多的情况，比如，实体不全（北京大学，但抽取出北京大）或者过长（北京，但北京大）呢？
> > 
> > 
> > 我记得代码结束后，out文件夹下会输出实体tag标签的预测结果，当初我检查的时候感觉这样的情况不多
> 
> > > > 模型流程是先进行命名实体识别，然后进行实体间的匹配(根据实体类型只匹配可能存在关系的实体），然后我将匹配出的两个实体和两个实体间的文字截取出来，使用CNN学习出一个特征向量，进行关系分类。
> > > > 不过我觉得这个设计可能并不是很好，因为结果只有0.81，我看比赛结果好多基于BERT的能够达到0.84，甚至0.86.
> > > 
> > > 
> > > 对的，我觉得是在实体对匹配过程，或者实体截取时除了问题，我这边recall很高，对分出来的错误实体简单过滤或者纠正，能提升2个点左右，你的这个模型可以在琢磨琢磨，有很大优化空间
> > 
> > 
> > 最近在准备保研的事情，等忙过这段时间，再好好研究一下排名靠前的BERT模型，如果您有优化，也希望您能指教，谢谢您，祝您生活愉快！
> 
> 你还是本科生啊，很厉害啊，你的这个模型是自己设计的吗，有参考文献吗？有的话希望能告知，也祝你保研顺利！

额，当时也就瞎看看。和这个模型相关的话，大概有这些资料吧。
- [解读pytorch Bert源码](https://zhuanlan.zhihu.com/p/56103665)
-  Joint entity and relation extraction based on a hybrid neural network
- [这里](https://blog.csdn.net/Wangpeiyi9979/article/details/89599009)有自己总结的BertForTokenClassification和pytorch-crf使用

当时还复现修改过其他的模型，可能是复现水平的问题，效果不是很好，就放弃了。大概有这些
- Joint Extraction of Multiple Relations and Entities by using a Hybrid Neural Network
- Joint Extraction of Entities and Relations Based on a Novel Tagging Scheme
Suncong
- Extracting Relational Facts by an End-to-End Neural Model with Copy Mechanism

**Comment by Wangpeiyi9979** [comment]
> @Wangpeiyi9979 祝顺

谢谢您
